##创建任务时 填好的


#git名称
git_project_name: LenzBusiness


#分支名称 
git_branch: feature/20190601_TimeManagement


#pm 可不填 自动从分支名称中获取
project_pm: 吕博涧


#项目名称 可不填 自动从分支名称中获取
project_name: 朗镜通iOS 朗镜通iOS 朗镜通iOS 朗镜通iOS 时间打点


#测试项
test_options: |
  1.崩溃预防
  2.时间打点业务



##提交的时候获取

#备注
poject_comment: |
  崩溃预防
  Merge branch 'master' into rtag_20190522_question_time_record_ios
  Merge branch 'master' into rtag_20190522_question_time_record_ios
  Merge branch 'feature/2019_05_14_吕博涧_时间打点' into rtag_20190522_question_time_record_ios
  Merge branch 'master' into feature/2019_05_14_吕博涧_时间打点

  Conflicts:
  	Podfile.lock
  	Pods/LenzQuestionBaseModule/LenzQuestionBaseModule/base/QuestionModule/questionBase/model/question/LenzBaseQuestion.m
  	Pods/Manifest.lock
  Merge branch 'feature/2019_05_14_question_time_record' into rtag_20190522_question_time_record_ios
  Fix
  时间打点 逻辑 说明
  Merge branch 'master' into feature/2019_05_14_question_time_record
  时间 打点逻辑优化
  时间打点
  时间打点


#开发人员 自动从git获取
project_developers: 仇友博

#pr
project_pr_diff: https://gitee.com/ppz_bj/LenzBusiness/pulls/7

#code review人员 可不填
review_members: ''

#ui
project_ui: 李娟

